name: transformers
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py38h32f6830_1
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py_2
  - dbus=1.13.12=h746ee38_0
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.1=he06d7ca_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=py38h73cb85d_1003
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - icu=58.2=hf484d3e_1000
  - intel-openmp=2020.0=166
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py38hbf85e49_1
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1006
  - libpng=1.6.37=hed695b0_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38hef1b27d_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.0.15=py38ha843d7b_0
  - mkl_random=1.1.0=py38h962f231_0
  - ncurses=6.2=he6710b0_0
  - ninja=1.9.0=py38hfd86e86_0
  - nltk=3.4.5=py38_0
  - numpy=1.18.1=py38h4f9e942_0
  - numpy-base=1.18.1=py38hde5b4d6_1
  - openssl=1.1.1e=h516909a_0
  - pandas=1.0.2=py38h0573a6f_0
  - pcre=8.44=he1b5a44_0
  - pip=20.0.2=py38_1
  - pthread-stubs=0.4=h14c3975_1001
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py38h05f1152_4
  - python=3.8.1=h0371630_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.4.0=py3.8_cuda10.0.130_cudnn7.6.3_0
  - pytz=2019.3=py_0
  - qt=5.9.7=h52cfd70_2
  - readline=7.0=h7b6447c_5
  - scipy=1.4.1=py38h0b6359f_0
  - setuptools=46.0.0=py38_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.4=py38h1e0a361_1
  - tqdm=4.43.0=py_0
  - wheel=0.34.2=py38_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.9.0
    - astunparse==1.6.3
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.4
    - bokeh==2.0.1
    - boto3==1.12.26
    - botocore==1.15.26
    - cachetools==4.0.0
    - cchardet==2.1.6
    - chardet==3.0.4
    - click==7.1.1
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dill==0.3.1.1
    - docutils==0.15.2
    - entrypoints==0.3
    - fastprogress==0.2.2
    - filelock==3.0.12
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.12.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - googleapis-common-protos==1.51.0
    - grpcio==1.27.2
    - h5py==2.10.0
    - idna==2.9
    - imbalanced-learn==0.7.0
    - imblearn==0.0
    - ipykernel==5.2.0
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - jedi==0.16.0
    - jieba==0.42.1
    - jinja2==2.11.1
    - jmespath==0.9.5
    - json5==0.9.3
    - jsonschema==3.2.0
    - jupyter-client==6.1.0
    - jupyter-core==4.6.3
    - jupyterlab==2.0.1
    - jupyterlab-server==1.0.7
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-bert==0.81.0
    - keras-embed-sim==0.7.0
    - keras-layer-normalization==0.14.0
    - keras-multi-head==0.22.0
    - keras-pos-embd==0.11.0
    - keras-position-wise-feed-forward==0.6.0
    - keras-preprocessing==1.1.0
    - keras-self-attention==0.41.0
    - keras-transformer==0.32.0
    - ktrain==0.12.2
    - langdetect==1.0.8
    - markdown==3.2.1
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.4
    - networkx==2.4
    - notebook==6.0.3
    - oauthlib==3.1.0
    - opt-einsum==3.2.0
    - packaging==20.3
    - pandocfilters==1.4.2
    - parso==0.6.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.1.0
    - prometheus-client==0.7.1
    - promise==2.3
    - prompt-toolkit==3.0.4
    - protobuf==3.11.3
    - ptyprocess==0.6.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.6.1
    - pyrsistent==0.15.7
    - pyyaml==5.3.1
    - pyzmq==19.0.0
    - regex==2020.2.20
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - s3transfer==0.3.3
    - sacremoses==0.0.38
    - scikit-learn==0.23.1
    - send2trash==1.5.0
    - sentencepiece==0.1.85
    - seqeval==0.0.12
    - syntok==1.2.2
    - tensorboard==2.2.0
    - tensorboard-plugin-wit==1.6.0.post2
    - tensorflow==2.2.0rc2
    - tensorflow-datasets==2.1.0
    - tensorflow-estimator==2.2.0rc0
    - tensorflow-metadata==0.21.1
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tokenizers==0.5.2
    - traitlets==4.3.3
    - transformers==2.7.0
    - typing-extensions==3.7.4.1
    - urllib3==1.25.8
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - wrapt==1.12.1
prefix: /data/dirksonar/miniconda3/envs/transformers

